CREATE TABLE PORC_BONO_ANNOS
(
    anno_ini        NUMBER,
    anno_ter        NUMBER,
    porcentaje_bono NUMBER

);

INSERT INTO PORC_BONO_ANNOS
VALUES (1,5,5);
INSERT INTO PORC_BONO_ANNOS
VALUES (6,10,7);
INSERT INTO PORC_BONO_ANNOS
VALUES (11,15,10);
INSERT INTO PORC_BONO_ANNOS
VALUES (16,20,12);
INSERT INTO PORC_BONO_ANNOS
VALUES (21,25,15);
INSERT INTO PORC_BONO_ANNOS
VALUES (26,30,20);
INSERT INTO PORC_BONO_ANNOS
VALUES (31,40,30);