CREATE USER    -- SENTENCIA PARA CREAR USUARIO
hr_11  -- NOMBRE DEL USUARIO
IDENTIFIED BY Duoc2021_MDY2131   -- SE ASIGNA LA CONTRASEÑA
; -- TERMINO DE LA SENTENCIA DE CREACION DE USUARIO
  
/*
     LOS USUARIO PARA PODER TRABAJAR EN 
     LA BASE DE DATOS DEBEN TENER 
     ALGUNOS PRIVILEGIOS Y PERMISOS
*/  
  
GRANT UNLIMITED TABLESPACE TO hr_11;  -- ASIGNA ESPACIO DE ALMACENAMIENTO AL USUARIO

GRANT CONNECT TO hr_11;   -- ASIGNACION DE PERMISO DE CONECCION A LA BASE DE DATOS

GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO hr_11;  -- ASIGNA PERMISOS DE  OBJETOS

GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE TO hr_11;  -- ASIGAN OTROS PERMISOS

ALTER USER hr_11 DEFAULT ROLE CONNECT, RESOURCE; -- SE ASIGNA ROLES AL USUARIO

COMMIT; -- SE CONFIRMAN LOS CAMBIOS EN LA BASE DE DATOS