/* Creación de usuarios si está trabajando con BD Oracle XE */
CREATE USER MDY3131_P9 IDENTIFIED BY "MDY3131.practica_9"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER MDY3131_P9 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO MDY3131_P9;
GRANT "RESOURCE" TO MDY3131_P9;
ALTER USER MDY3131_P9 DEFAULT ROLE "RESOURCE";


/* Creación de usuarios si está trabajando con BD Oracle Cloud */
CREATE USER MDY3131_P9 IDENTIFIED BY "MDY3131.practica_9"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER MDY3131_P9 QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO MDY3131_P9;
GRANT "RESOURCE" TO MDY3131_P9;
ALTER USER MDY3131_P9 DEFAULT ROLE "RESOURCE";