/* Creación de usuario si está trabajando con BD Oracle XE */
CREATE USER PRUEBA_P1 IDENTIFIED BY "MDY3131.prueba_1"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER PRUEBA_P1 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO PRUEBA_P1;
GRANT "RESOURCE" TO PRUEBA_P1;
ALTER USER PRUEBA_P1 DEFAULT ROLE "RESOURCE";

/* Creación de usuario si está trabajando con BD Oracle Cloud */
CREATE USER PRUEBA_P1 IDENTIFIED BY "MDY3131.prueba_1"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER PRUEBA_P1 QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO PRUEBA_P1;
GRANT "RESOURCE" TO PRUEBA_P1;
ALTER USER PRUEBA_P1 DEFAULT ROLE "RESOURCE";