/* Dropeo de tablas */
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FactBOLETA]') AND type in (N'U')) DROP TABLE [dbo].[FactBOLETA]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimVENTA]') AND type in (N'U')) DROP TABLE [dbo].[DimVENTA]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimFECHA]') AND type in (N'U')) DROP TABLE [dbo].[DimFECHA]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimANNO]') AND type in (N'U')) DROP TABLE [dbo].[DimANNO]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimMES]') AND type in (N'U')) DROP TABLE [dbo].[DimMES]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimDIA]') AND type in (N'U')) DROP TABLE [dbo].[DimDIA]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimHORA]') AND type in (N'U')) DROP TABLE [dbo].[DimHORA]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimPRODUCTO]') AND type in (N'U')) DROP TABLE [dbo].[DimPRODUCTO]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimCATEGORIA]') AND type in (N'U')) DROP TABLE [dbo].[DimCATEGORIA]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimVENDEDOR]') AND type in (N'U')) DROP TABLE [dbo].[DimVENDEDOR]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimCLIENTE]') AND type in (N'U')) DROP TABLE [dbo].[DimCLIENTE]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimDATOS]') AND type in (N'U')) DROP TABLE [dbo].[DimDATOS]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimCONTACTO]') AND type in (N'U')) DROP TABLE [dbo].[DimCONTACTO]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimDIRECCIONCLIENTE]') AND type in (N'U')) DROP TABLE [dbo].[DimDIRECCIONCLIENTE]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimREGION_CLIENTE]') AND type in (N'U')) DROP TABLE [dbo].[DimREGION_CLIENTE]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimCODIGOPOSTALCLIENTE]') AND type in (N'U')) DROP TABLE [dbo].[DimCODIGOPOSTALCLIENTE]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimCALLECLIENTE]') AND type in (N'U')) DROP TABLE [dbo].[DimCALLECLIENTE]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimCOMUNACLIENTE]') AND type in (N'U')) DROP TABLE [dbo].[DimCOMUNACLIENTE]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimCIUDADCLIENTE]') AND type in (N'U')) DROP TABLE [dbo].[DimCIUDADCLIENTE]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimSUCURSAL]') AND type in (N'U')) DROP TABLE [dbo].[DimSUCURSAL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimDIRECCIONSUCURSAL]') AND type in (N'U')) DROP TABLE [dbo].[DimDIRECCIONSUCURSAL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimREGIONSUCURSAL]') AND type in (N'U')) DROP TABLE [dbo].[DimREGIONSUCURSAL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimCODIGOPOSTALSUCURSAL]') AND type in (N'U')) DROP TABLE [dbo].[DimCODIGOPOSTALSUCURSAL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimCALLESUCURSAL]') AND type in (N'U')) DROP TABLE [dbo].[DimCALLESUCURSAL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimCOMUNASUCURSAL]') AND type in (N'U')) DROP TABLE [dbo].[DimCOMUNASUCURSAL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DimCIUDADSUCURSAL]') AND type in (N'U')) DROP TABLE [dbo].[DimCIUDADSUCURSAL]


-- /*
-- CREACION DE TABLAS
-- ESQUEMA COPO DE NIEVE
-- TABLA DE HECHO: FactBOLETA

-- PARTO HACIENDO LAS BOLETAS DE CAPA EXTERIOR
-- */

CREATE TABLE DimREGIONSUCURSAL(
	ID_REGION				    NUMERIC(2,0)    NOT NULL IDENTITY(1,1)  PRIMARY KEY,
	NOMBRE_REGION			    NVARCHAR(255)
);
CREATE TABLE DimCODIGOPOSTALSUCURSAL(
	ID_CODIGO_POSTAL			    NUMERIC(3,0)    NOT NULL IDENTITY(1,1)  PRIMARY KEY,
	CODIGO_POSTAL			    NUMERIC(7,0)
);
CREATE TABLE DimCALLESUCURSAL(
	ID_CALLE_SUCURSAL		    NUMERIC(3,0)    NOT NULL IDENTITY(1,1)  PRIMARY KEY,
	NOMBRE_CALLE			    NVARCHAR(255),
);
CREATE TABLE DimCOMUNASUCURSAL(
	ID_COMUNA_SUCURSAL		    NUMERIC(3,0)    NOT NULL IDENTITY(1,1)  PRIMARY KEY,
	NOMBRE_COMUNA			    NVARCHAR(255)
);
CREATE TABLE DimCIUDADSUCURSAL(
	ID_CIUDAD_SUCURSAL		    NUMERIC(3,0)    NOT NULL IDENTITY(1,1)  PRIMARY KEY,
	NOMBRE_CIUDAD_SUCURSAL	    NVARCHAR(255)
);
CREATE TABLE DimDIRECCIONSUCURSAL(
	ID_DIRECCION_SUCURSAL	    NUMERIC(2,0)    NOT NULL IDENTITY(1,1)  PRIMARY KEY,
	ID_REGION_SUCURSAL  	    NUMERIC(2,0),
    ID_CODIGO_POSTAL_SUCURSAL	NUMERIC(3,0),
    ID_CALLE_SUCURSAL		    NUMERIC(3,0),
    ID_COMUNA_SUCURSAL		    NUMERIC(3,0),
    ID_CIUDAD_SUCURSAL		    NUMERIC(3,0),
    NUMERODOMICILIO             NUMERIC(5,0),
    CONSTRAINT FK_REGION_SUCURSAL_DIRECCION_SUCURSAL FOREIGN KEY (ID_REGION_SUCURSAL) REFERENCES DimREGIONSUCURSAL(ID_REGION),
    CONSTRAINT FK_CODIGO_POSTAL_SUCURSAL_DIRECCION_SUCURSAL FOREIGN KEY (ID_CODIGO_POSTAL_SUCURSAL) REFERENCES DimCODIGOPOSTALSUCURSAL(ID_CODIGO_POSTAL),
    CONSTRAINT FK_CALLE_SUCURSAL_DIRECCION_SUCURSAL FOREIGN KEY (ID_CALLE_SUCURSAL) REFERENCES DimCALLESUCURSAL(ID_CALLE_SUCURSAL),
    CONSTRAINT FK_COMUNA_SUCURSAL_DIRECCION_SUCURSAL FOREIGN KEY (ID_COMUNA_SUCURSAL) REFERENCES DimCOMUNASUCURSAL(ID_COMUNA_SUCURSAL),
    CONSTRAINT FK_CIUDAD_SUCURSAL_DIRECCION_SUCURSAL FOREIGN KEY (ID_CIUDAD_SUCURSAL) REFERENCES DimCIUDADSUCURSAL(ID_CIUDAD_SUCURSAL)
);
CREATE TABLE DimSUCURSAL(
    ID_SUCURSAL				    NUMERIC(3,0)	NOT NULL IDENTITY(1,1)  PRIMARY KEY,
    ID_DIRECCION_SUCURSAL	    NUMERIC(2,0),
    NOMBRE                      NVARCHAR(255),
    CONSTRAINT FK_DIRECCION_SUCURSAL_SUCURSAL FOREIGN KEY (ID_DIRECCION_SUCURSAL) REFERENCES DimDIRECCIONSUCURSAL(ID_DIRECCION_SUCURSAL)
);
--
CREATE TABLE DimCIUDADCLIENTE(
    ID_CIUDAD_CLIENTE		    NUMERIC(5,0)	NOT NULL IDENTITY(1,1)  PRIMARY KEY,
    NOMBRE_CIUDAD_CLIENTE	    NVARCHAR(255)
);
CREATE TABLE DimCOMUNACLIENTE(
    ID_COMUNA_CLIENTE		    NUMERIC(5,0)	NOT NULL IDENTITY(1,1)  PRIMARY KEY,
    NOMBRE_COMUNA_CLIENTE	    NVARCHAR(255)
);
CREATE TABLE DimCALLECLIENTE(
    ID_CALLE_CLIENTE		    NUMERIC(5,0)	NOT NULL IDENTITY(1,1)  PRIMARY KEY,
    NOMBRE_CALLE_CLIENTE	    NVARCHAR(255)
);

CREATE TABLE DimCODIGOPOSTALCLIENTE(
    ID_CODIGO_POSTAL_CLIENTE	NUMERIC(7,0)	NOT NULL IDENTITY(1,1)  PRIMARY KEY,
    CODIGO_POSTAL_CLIENTE	    NUMERIC(7,0)
);
CREATE TABLE DimREGION_CLIENTE(
    ID_REGION_CLIENTE		    NUMERIC(2,0)	NOT NULL IDENTITY(1,1)  PRIMARY KEY,
    NOMBRE_REGION_CLIENTE	    NVARCHAR(255)
);
CREATE TABLE DimDIRECCIONCLIENTE(
    ID_DIRECCION_CLIENTE	    NUMERIC(5,0)	NOT NULL IDENTITY(1,1)  PRIMARY KEY,
    ID_REGION_CLIENTE		    NUMERIC(2,0),
    ID_CODIGO_POSTAL_CLIENTE	NUMERIC(7,0),
    ID_CALLE_CLIENTE		    NUMERIC(5,0),
    ID_COMUNA_CLIENTE		    NUMERIC(5,0),
    ID_CIUDAD_CLIENTE		    NUMERIC(5,0),
    NUMERODOMICILIO_CLIENTE     NUMERIC(5,0),
    CONSTRAINT FK_REGION_CLIENTE_DIRECCION_CLIENTE FOREIGN KEY (ID_REGION_CLIENTE) REFERENCES DimREGION_CLIENTE(ID_REGION_CLIENTE),
    CONSTRAINT FK_CODIGO_POSTAL_CLIENTE_DIRECCION_CLIENTE FOREIGN KEY (ID_CODIGO_POSTAL_CLIENTE) REFERENCES DimCODIGOPOSTALCLIENTE(ID_CODIGO_POSTAL_CLIENTE),
    CONSTRAINT FK_CALLE_CLIENTE_DIRECCION_CLIENTE FOREIGN KEY (ID_CALLE_CLIENTE) REFERENCES DimCALLECLIENTE(ID_CALLE_CLIENTE),
    CONSTRAINT FK_COMUNA_CLIENTE_DIRECCION_CLIENTE FOREIGN KEY (ID_COMUNA_CLIENTE) REFERENCES DimCOMUNACLIENTE(ID_COMUNA_CLIENTE),
    CONSTRAINT FK_CIUDAD_CLIENTE_DIRECCION_CLIENTE FOREIGN KEY (ID_CIUDAD_CLIENTE) REFERENCES DimCIUDADCLIENTE(ID_CIUDAD_CLIENTE)
);
CREATE TABLE DimCONTACTO(
    ID_CONTACTO			NUMERIC(5,0)	NOT NULL IDENTITY(1,1)  PRIMARY KEY,
    TELEFONO		    NUMERIC(9,0),
    CORREO			    NVARCHAR(255)
);
CREATE TABLE DimDATOS(
    ID_DATOS            NUMERIC(5,0)	NOT NULL IDENTITY(1,1)  PRIMARY KEY,
    RUT                 NVARCHAR(255)    UNIQUE,
    NOMBRE              NVARCHAR(255),
    APELLIDO            NVARCHAR(255),
    FECHA_NACIMIENTO    DATE
);
CREATE TABLE DimCLIENTE(
    ID_CLIENTE        NUMERIC(5,0)	NOT NULL IDENTITY(1,1)  PRIMARY KEY,
    DATOS_ID          NUMERIC(5,0),
    CONTACTO_ID       NUMERIC(5,0),
    DIRECCION_ID      NUMERIC(5,0),
    CONSTRAINT FK_DATOS_CLIENTE FOREIGN KEY (DATOS_ID) REFERENCES DimDATOS(ID_DATOS),
    CONSTRAINT FK_CONTACTO_CLIENTE FOREIGN KEY (CONTACTO_ID) REFERENCES DimCONTACTO(ID_CONTACTO),
    CONSTRAINT FK_DIRECCION_CLIENTE FOREIGN KEY (DIRECCION_ID) REFERENCES DimDIRECCIONCLIENTE(ID_DIRECCION_CLIENTE)
);
--
CREATE TABLE DimVENDEDOR(
    ID_VENDEDOR         NUMERIC(4,0)	NOT NULL IDENTITY(1,1)  PRIMARY KEY,
    NOMBRE_VENDEDOR     NVARCHAR(255),
    APELLIDO_VENDEDOR   NVARCHAR(255),
);
--
CREATE TABLE DimCATEGORIA(
    ID_CATEGORIA            NUMERIC(2,0)	NOT NULL IDENTITY(1,1)  PRIMARY KEY,
    NOMBRE_CATEGORIA        NVARCHAR(255),
    DESCRIPCION_CATEGORIA   NVARCHAR(255)
);
CREATE TABLE DimPRODUCTO(
    ID_PRODUCTO             NUMERIC(2,0)	NOT NULL IDENTITY(1,1)  PRIMARY KEY,
    NOMBRE_PRODUCTO         NVARCHAR(255),
    DESCRIPCION_PRODUCTO    NVARCHAR(255),
    ID_CATEGORIA_PRODUCTO            NUMERIC(2,0),
    CONSTRAINT FK_CATEGORIA_PRODUCTO FOREIGN KEY (ID_CATEGORIA_PRODUCTO) REFERENCES DimCATEGORIA(ID_CATEGORIA)
);
CREATE TABLE DimHORA(
    ID_HORA         NUMERIC(10,0)	NOT NULL IDENTITY(1,1)  PRIMARY KEY,
    HORA            TIME
);
CREATE TABLE DimDIA(
    ID_DIA          NUMERIC(10,0)	NOT NULL IDENTITY(1,1)  PRIMARY KEY,
    DIA             NUMERIC(2,0)
);
CREATE TABLE DimMES(
    ID_MES          NUMERIC(10,0)	NOT NULL IDENTITY(1,1)  PRIMARY KEY,
    MES             NUMERIC(2,0)
);
CREATE TABLE DimANNO(
    ID_ANNO         NUMERIC(10,0)	NOT NULL IDENTITY(1,1)  PRIMARY KEY,
    ANNO            NUMERIC(4,0)
);
CREATE TABLE DimFECHA(
    ID_FECHA        NUMERIC(8,0)	NOT NULL IDENTITY(1,1)  PRIMARY KEY,
    ID_ANNO         NUMERIC(10,0),
    ID_MES          NUMERIC(10,0),
    ID_DIA          NUMERIC(10,0),
    ID_HORA         NUMERIC(10,0),
    CONSTRAINT FK_ANNO_FECHA FOREIGN KEY (ID_ANNO) REFERENCES DimANNO(ID_ANNO),
    CONSTRAINT FK_MES_FECHA FOREIGN KEY (ID_MES) REFERENCES DimMES(ID_MES),
    CONSTRAINT FK_DIA_FECHA FOREIGN KEY (ID_DIA) REFERENCES DimDIA(ID_DIA),
    CONSTRAINT FK_HORA_FECHA FOREIGN KEY (ID_HORA) REFERENCES DimHORA(ID_HORA)
);
CREATE TABLE DimVENTA(
    ID_VENTA                NUMERIC(7,0)	NOT NULL IDENTITY(1,1)  PRIMARY KEY,
    ID_PRODUCTO             NUMERIC(2,0),
    ID_FECHA                NUMERIC(8,0),
    PRECIO_UNITARIO         NUMERIC(7,0),
    CANTIDAD                NUMERIC(7,0),
    DESCUENTO               NUMERIC(4,2),
    PRECIO_TOTAL            NUMERIC(8,0),
    CONSTRAINT FK_PRODUCTO_VENTA FOREIGN KEY (ID_PRODUCTO) REFERENCES DimPRODUCTO(ID_PRODUCTO),
    CONSTRAINT FK_FECHA_VENTA FOREIGN KEY (ID_FECHA) REFERENCES DimFecha(ID_FECHA)
);
--

--
-- CREATE TABLE FactBOLETA(
--     --ID_BOLETA       NUMERIC(7,0)	NOT NULL IDENTITY(1,1)  PRIMARY KEY,
--     ID_CLIENTE      NUMERIC(5,0),
--     ID_VENDEDOR     NUMERIC(4,0),
--     ID_FECHA        NUMERIC(8,0)	NOT NULL IDENTITY(1,1),
--     ID_SUCURSAL     NUMERIC(3,0),
--     ID_VENTA        NUMERIC(7,0),
--     CONSTRAINT FK_CLIENTE_BOLETA FOREIGN KEY (ID_CLIENTE) REFERENCES DimCLIENTE(ID_CLIENTE),
--     CONSTRAINT FK_VENDEDOR_BOLETA FOREIGN KEY (ID_VENDEDOR) REFERENCES DimVENDEDOR(ID_VENDEDOR),
--     --CONSTRAINT FK_FECHA_BOLETA FOREIGN KEY (ID_FECHA) REFERENCES DimFECHA(ID_FECHA),
--     CONSTRAINT FK_SUCURSAL_BOLETA FOREIGN KEY (ID_SUCURSAL) REFERENCES DimSUCURSAL(ID_SUCURSAL),
--     CONSTRAINT FK_VENTA_BOLETA FOREIGN KEY (ID_VENTA) REFERENCES DimVENTA(ID_VENTA)
-- );
CREATE TABLE FactBOLETA(
    --ID_BOLETA       NUMERIC(7,0)	NOT NULL IDENTITY(1,1)  PRIMARY KEY,
    ID_CLIENTE      NUMERIC(5,0),
    ID_VENDEDOR     NUMERIC(4,0),
    ID_FECHA        NUMERIC(8,0),
    ID_SUCURSAL     NUMERIC(3,0),
    ID_VENTA        NUMERIC(7,0),
    CONSTRAINT FK_CLIENTE_BOLETA FOREIGN KEY (ID_CLIENTE) REFERENCES DimCLIENTE(ID_CLIENTE),
    CONSTRAINT FK_VENDEDOR_BOLETA FOREIGN KEY (ID_VENDEDOR) REFERENCES DimVENDEDOR(ID_VENDEDOR),
    --CONSTRAINT FK_FECHA_BOLETA FOREIGN KEY (ID_FECHA) REFERENCES DimFECHA(ID_FECHA),
    CONSTRAINT FK_SUCURSAL_BOLETA FOREIGN KEY (ID_SUCURSAL) REFERENCES DimSUCURSAL(ID_SUCURSAL),
    CONSTRAINT FK_VENTA_BOLETA FOREIGN KEY (ID_VENTA) REFERENCES DimVENTA(ID_VENTA)
);


