/* Creación de usuario si está trabajando con BD Oracle XE */
CREATE USER ETMDY_FA IDENTIFIED BY "MDY3131.ETMDY_FA"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER ETMDY_FA QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO ETMDY_FA;
GRANT "RESOURCE" TO ETMDY_FA;
ALTER USER ETMDY_FA DEFAULT ROLE "RESOURCE";

/* Creación de usuario si está trabajando con BD Oracle Cloud */
CREATE USER ETMDY_FA IDENTIFIED BY "MDY3131.ETMDY_FA"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER ETMDY_FA  QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO ETMDY_FA;
GRANT "RESOURCE" TO ETMDY_FA;
ALTER USER ETMDY_FA  DEFAULT ROLE "RESOURCE";