--CASO 4
SELECT 
'El empleado '||upper(NOMBRE)||' '||upper(PATERNO)||' '||
upper(MATERNO)||' está de cumpleaños el '||TO_CHAR(fecnac,'DD')||' de '||INITCAP(TO_CHAR(fecnac,'MONTH'))||'. Cumple '||
trunc(MONTHS_BETWEEN(SYSDATE,FECNAC)/12)||' años.' as "LISTADO DE CUMPLEAÑOS"
FROM EMPLEADO
ORDER BY TO_NUMBER(TO_CHAR(FECNAC,'DD'));

--CASO 5
--Primera opcion
SELECT 
SUBSTR(RUTEMP,1,8)||'-'||SUBSTR(RUTEMP,-1) AS "RUN EMPLEADO",
NOMBRE||' '||PATERNO||' '||MATERNO AS "NOMBRE EMPLEADO",
RTRIM(TO_CHAR(SUELDO,'$9G999G999')) AS "SALARIO ACTUAL",
--aumentar un 13% al sueldo
TO_CHAR(SUELDO*1.13,'$9G999G999') AS "SUELDO REAJUSTADO",
--extraer un 13% al sueldo reajustado
TO_CHAR(SUELDO*0.13,'$9G999G999') AS "AUMENTO"
FROM EMPLEADO
ORDER BY PATERNO;

--Segunda opcion
SELECT 
SUBSTR(RUTEMP,1,8)||'-'||SUBSTR(RUTEMP,-1) AS "RUN EMPLEADO",
NOMBRE||' '||PATERNO||' '||MATERNO AS "NOMBRE EMPLEADO",
RTRIM(TO_CHAR(SUELDO,'$9G999G999')) AS "SALARIO ACTUAL",
TRUNC(MONTHS_BETWEEN(SYSDATE,FECING)/12) AS "AÑOS TRABAJADOS",
TRIM(TO_CHAR(SUELDO*((TRUNC(MONTHS_BETWEEN(SYSDATE,FECING)/12)/100)+1),'$9G999G999')) AS "SUELDO REAJUSTADO",
TRIM(TO_CHAR(SUELDO*((TRUNC(MONTHS_BETWEEN(SYSDATE,FECING)/12)/100)),'$9G999G999')) as AUMENTO
FROM EMPLEADO
ORDER BY PATERNO;

--CASO 6

SELECT 
TO_CHAR(SUBSTR(RUTCLI,1,LENGTH(RUTCLI)-1),'09G999G999')||'-'||SUBSTR(RUTCLI,LENGTH(RUTCLI),1) AS "RUN CLIENTE",
--INSTR(NOMCLI,' ') as flag1,
--INSTR(NOMCLI,' ',1,2) as flag1,
--NOMCLI,
INITCAP(CASE INSTR(NOMCLI,' ')
            WHEN 5 THEN TRIM(SUBSTR(NOMCLI,1,4)) 
            WHEN 6 THEN TRIM(SUBSTR(NOMCLI,1,5)) 
            WHEN 7 THEN TRIM(SUBSTR(NOMCLI,1,6))
            WHEN 8 THEN TRIM(SUBSTR(NOMCLI,1,7))
            WHEN 9 THEN TRIM(SUBSTR(NOMCLI,1,8))
            WHEN 10 THEN TRIM(SUBSTR(NOMCLI,1,9))
            WHEN 11 THEN TRIM(SUBSTR(NOMCLI,1,10))
            WHEN 12 THEN TRIM(SUBSTR(NOMCLI,1,11))
        END ||' '||
        CASE INSTR(NOMCLI,' ')
            WHEN 5 THEN TRIM(SUBSTR(NOMCLI,6,1))
            WHEN 6 THEN TRIM(SUBSTR(NOMCLI,7,1))
            WHEN 7 THEN TRIM(SUBSTR(NOMCLI,8,1))
            WHEN 8 THEN TRIM(SUBSTR(NOMCLI,9,1))
            WHEN 9 THEN TRIM(SUBSTR(NOMCLI,10,1))
            WHEN 10 THEN TRIM(SUBSTR(NOMCLI,11,1))
            WHEN 11 THEN TRIM(SUBSTR(NOMCLI,12,1))
            WHEN 12 THEN TRIM(SUBSTR(NOMCLI,13,1))
        END ||'. '||
        CASE INSTR(NOMCLI,' ',1,2)
            WHEN 12 THEN TRIM(SUBSTR(NOMCLI,13))
            WHEN 13 THEN TRIM(SUBSTR(NOMCLI,14))
            WHEN 14 THEN TRIM(SUBSTR(NOMCLI,15))
            WHEN 15 THEN TRIM(SUBSTR(NOMCLI,16))
            WHEN 16 THEN TRIM(SUBSTR(NOMCLI,17))
            WHEN 17 THEN TRIM(SUBSTR(NOMCLI,18))
            WHEN 18 THEN TRIM(SUBSTR(NOMCLI,19))
            WHEN 19 THEN TRIM(SUBSTR(NOMCLI,20))
            WHEN 21 THEN TRIM(SUBSTR(NOMCLI,22))
        END) AS "NOMBRE CLIENTE",
ECIVIL AS "ESTADO CIVIL",
TO_CHAR(RENTAMAXIMA,'$9,999,999') AS RENTA,
NVL(FONO1,'NO POSEE FONO FIJO PARA CONTACTARLO') AS "FONO FIJO",
NVL(FONO2,'NO POSEE CELULAR PARA CONTACTARLO') AS "CELULAR"
FROM CLIENTE
WHERE ((ECIVIL='Separado' OR ECIVIL='Divorciado') AND RENTAMAXIMA>800000) OR ECIVIL='Soltero'
ORDER BY 1;




