# Generated by Django 4.0.4 on 2022-07-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityPlant', '0012_rename_suscripcion_usuarios_suscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='Suscripcion',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='suscripcion',
            field=models.BooleanField(default=False, verbose_name='membresia'),
        ),
    ]
